import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);
  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("renders the planning model shell", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);
  const html = await response.text();
  assert.match(html, /<html lang="ja">/i);
  assert.match(html, /<title>成長投資計画 数値設計ラボ<\/title>/i);
  assert.match(html, /成長投資計画 数値設計ラボ/);
  assert.doesNotMatch(html, /目標に近づける/);
  assert.match(html, /15指標・目標/);
  const pageSource = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const inputValueSource = await readFile(new URL("../app/input-values.ts", import.meta.url), "utf8");
  const metricGroupSource = await readFile(new URL("../app/metric-groups.ts", import.meta.url), "utf8");
  const proposalSource = await readFile(new URL("../app/proposal-io.ts", import.meta.url), "utf8");
  const globalStyles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  assert.match(pageSource, /設定した目標に近づける/);
  assert.match(pageSource, /projectSalesGrowth: \{ initial: 0\.22, lower: 0\.15, upper: 0\.30 \}/);
  assert.match(pageSource, /その他事業｜設備導入期間/);
  assert.match(pageSource, /その他事業｜基準年後/);
  assert.match(pageSource, /applyOtherSynergyLift\("otherSalesGrowth", "otherSalesGrowthToBase", 0\.02\)/);
  assert.match(pageSource, /設備導入期間＋2\.0pt/);
  assert.match(pageSource, /補助事業とのシナジーを見込み/);
  assert.match(pageSource, /projectPayGrowth: \{ initial: 0\.07, lower: 0\.05, upper: 0\.10 \}/);
  assert.match(pageSource, /projectCogsImprovementAfterBase: \{ initial: 0\.015, lower: 0, upper: 0\.03 \}/);
  assert.match(pageSource, /設備導入期間0～2pt、基準年後0～3pt/);
  assert.match(pageSource, /const improvementDriverKeys/);
  assert.match(pageSource, /keys: \["projectMarketGrowth", "subsidy"\]/);
  assert.match(pageSource, /ローカルベンチマーク固定値/);
  assert.match(pageSource, /固定入力・判定対象外/);
  assert.match(pageSource, /key === "investment" \|\| key === "usefulLife" \|\| key === "projectMarketGrowth"/);
  assert.match(pageSource, /calculateScaleDependentTargetDefaults/);
  assert.match(pageSource, /15指標の増加額5項目は固定中央値を使わず/);
  assert.match(pageSource, /デフォルト設定後に算出/);
  assert.doesNotMatch(pageSource, /原価率改善 1\.5pt［-2～5pt］/);
  assert.match(pageSource, /5ji_median\.pdf/);
  assert.match(pageSource, /補助事業1人当たり給与支給総額の年平均上昇率/);
  assert.doesNotMatch(pageSource, /1人給与成長率|1人給与伸び/);
  assert.match(pageSource, /その他販管費率改善ポイント/);
  assert.match(pageSource, /各期率＋前年差改善pt/);
  assert.match(pageSource, /<strong>\{improvementLabel\}<\/strong><small>当期率/);
  assert.match(pageSource, /actuals-three-year-table/);
  assert.match(pageSource, /content-stack history-actuals-view/);
  assert.match(pageSource, /function roundedInput\(value: number, digits = 2\)/);
  assert.match(pageSource, /上書き内容を反映して再最適化/);
  assert.match(pageSource, /15指標・目標へ戻る/);
  assert.match(pageSource, />基準年売上開始<\/button>/);
  assert.match(pageSource, /window\.scrollTo\(\{ top: 0, left: 0, behavior: "auto" \}\)/);
  assert.match(pageSource, /function DiagnosticCharts\(\{ plan \}/);
  assert.match(pageSource, /主要指標の推移チャート/);
  assert.match(pageSource, /人員・1人当たり給与/);
  assert.match(pageSource, /労働生産性/);
  assert.match(globalStyles, /\.diagnostic-chart-grid/);
  assert.doesNotMatch(pageSource, /onClick=\{\(\) => setView\(/);
  assert.doesNotMatch(pageSource, /function solveAndOpenAnnualPl\(\)/);
  assert.doesNotMatch(pageSource, /toFixed\(6\)/);
  assert.doesNotMatch(pageSource, /blankableInput/);
  assert.match(pageSource, /inputValues: clone\(inputValues\)/);
  assert.match(pageSource, /event\.target\.value === "" \? null/);
  assert.match(inputValueSource, /A missing key means "not entered"/);
  assert.match(inputValueSource, /else next\[key\] = value/);
  assert.match(proposalSource, /入力データ監査（Null／0区別）/);
  assert.match(pageSource, /metric-group-controls/);
  assert.match(pageSource, /proposal-action-menu/);
  assert.match(pageSource, /document\.addEventListener\("pointerdown", closeProposalMenus\)/);
  assert.match(pageSource, /event\.key !== "Escape"/);
  assert.match(pageSource, /keepOnlyProposalMenuOpen/);
  assert.match(pageSource, />出力 <span aria-hidden="true">▾<\/span>/);
  assert.match(pageSource, />サンプル <span aria-hidden="true">▾<\/span>/);
  assert.doesNotMatch(pageSource, />HTML出力<\/button>/);
  assert.match(globalStyles, /proposal-action-menu-items/);
  assert.match(globalStyles, /grid-template-columns: repeat\(auto-fit, minmax\(230px, 300px\)\)/);
  assert.match(globalStyles, /metric-group-control select \{ width: 100%; max-width: none;/);
  assert.match(pageSource, /に目標設定/);
  assert.match(pageSource, /2指標を同時に最適化/);
  assert.match(pageSource, /最適化結果/);
  assert.match(pageSource, /自動算出/);
  assert.match(pageSource, /個別に目標設定/);
  assert.match(globalStyles, /metric-independent-row/);
  assert.match(globalStyles, /targets-table thead th:nth-child\(2\), \.targets-table td:nth-child\(2\) \{ text-align: left; \}/);
  assert.match(pageSource, /14・15の役員関連2指標は第6次の評価対象外/);
  assert.match(pageSource, /reference-metric-row/);
  assert.match(proposalSource, /参考値・第6次評価対象外/);
  assert.match(pageSource, /同額ペースの\{targetComparisonYears\}年単純換算/);
  assert.match(pageSource, /基準年→事業化報告3年目/);
  assert.match(pageSource, /指標・第6次定義/);
  assert.match(pageSource, /第6次定義：\{definition\.round6Formula\}/);
  assert.match(proposalSource, /指標・第6次定義/);
  assert.match(proposalSource, /item\.round6Formula/);
  assert.doesNotMatch(proposalSource, /目標下限（3年間）/);
  assert.doesNotMatch(pageSource, />両方を制約</);
  assert.match(pageSource, /metricBasisRole\(key, metricGroupBases\) !== "result"/);
  assert.match(metricGroupSource, /companySalesCagr/);
  assert.match(metricGroupSource, /companySalesIncrease/);
  assert.match(metricGroupSource, /type MetricGroupBasis = "rate" \| "amount" \| "both"/);
  assert.match(globalStyles, /actuals-three-year-table \{ overflow-x: hidden; overflow-y: auto; \}/);
  assert.doesNotMatch(html, /codex-preview|react-loading-skeleton/i);
});
