import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);
  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("renders the planning model shell", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);
  const html = await response.text();
  assert.match(html, /<html lang="ja">/i);
  assert.match(html, /<title>成長投資計画 数値設計ラボ<\/title>/i);
  assert.match(html, /成長投資計画 数値設計ラボ/);
  assert.doesNotMatch(html, /目標に近づける/);
  assert.match(html, /15指標・目標/);
  const pageSource = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const modelSource = await readFile(new URL("../app/model.ts", import.meta.url), "utf8");
  const inputValueSource = await readFile(new URL("../app/input-values.ts", import.meta.url), "utf8");
  const metricGroupSource = await readFile(new URL("../app/metric-groups.ts", import.meta.url), "utf8");
  const proposalSource = await readFile(new URL("../app/proposal-io.ts", import.meta.url), "utf8");
  const reportDataSource = await readFile(new URL("../app/report-data.ts", import.meta.url), "utf8");
  const sampleProposalSource = await readFile(new URL("../app/sample-proposals.ts", import.meta.url), "utf8");
  const applicationRulesSource = await readFile(new URL("../app/application-rules.ts", import.meta.url), "utf8");
  const globalStyles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  const initialInputFunction = pageSource.match(/function createInitialInputValues\(\): InputValues \{[\s\S]*?\n\}/)?.[0] ?? "";
  assert.doesNotMatch(initialInputFunction, /driverRange/);
  assert.match(pageSource, /forecastSettingsStarted/);
  assert.match(pageSource, /forecastSettingsReady/);
  assert.match(pageSource, /将来予測の水準が指定済みです。過去データを基にした推奨値に変更してよろしいですか？/);
  assert.match(pageSource, /将来予測・調整水準が未設定です。/);
  assert.match(pageSource, /設定した目標に近づける/);
  assert.match(pageSource, /projectSalesGrowth: \{ initial: 0\.22, lower: 0\.15, upper: 0\.30 \}/);
  assert.match(pageSource, /その他事業｜設備導入期間/);
  assert.match(pageSource, /その他事業｜基準年後/);
  assert.match(pageSource, /applyOtherSynergyLift\("otherSalesGrowth", "otherSalesGrowthToBase", 0\.02\)/);
  assert.match(pageSource, /設備導入期間＋2\.0pt/);
  assert.match(pageSource, /補助事業とのシナジーを見込み/);
  assert.match(pageSource, /projectPayGrowth: \{ initial: 0\.07, lower: 0\.05, upper: 0\.10 \}/);
  assert.match(pageSource, /benchmark && key !== "projectOfficerPayGrowth"/);
  assert.doesNotMatch(pageSource, /nextDrivers\.projectOfficerPayGrowth = nextDrivers\.projectPayGrowth/);
  assert.doesNotMatch(pageSource, /nextDrivers\.projectOfficerPayGrowthToBase = nextDrivers\.projectPayGrowthToBase/);
  assert.match(pageSource, /過去3期の役員1人当たり給与から推計/);
  assert.match(pageSource, /projectCogsImprovementAfterBase: \{ initial: 0\.015, lower: 0, upper: 0\.03 \}/);
  assert.match(pageSource, /設備導入期間0～2pt、基準年後0～3pt/);
  assert.match(pageSource, /const improvementDriverKeys/);
  assert.match(pageSource, /"investment", "subsidy", "usefulLife"/);
  assert.match(pageSource, /keys: \["projectMarketGrowth"\]/);
  assert.match(pageSource, /ローカルベンチマーク固定値/);
  assert.match(pageSource, /固定入力・判定対象外/);
  assert.match(pageSource, /key === "investment" \|\| key === "subsidy" \|\| key === "usefulLife" \|\| key === "projectMarketGrowth"/);
  assert.match(pageSource, /市場伸び率・補助事業投資額・申請補助金額・耐用年数は固定入力/);
  assert.match(proposalSource, /\["investment", "subsidy", "usefulLife", "projectMarketGrowth"\]\.includes\(key\) \? undefined/);
  assert.match(pageSource, /calculateScaleDependentTargetDefaults/);
  assert.match(pageSource, /15指標の増加額5項目は固定中央値を使わず/);
  assert.match(pageSource, /デフォルト設定後に算出/);
  assert.doesNotMatch(pageSource, /原価率改善 1\.5pt［-2～5pt］/);
  assert.match(pageSource, /5ji_median\.pdf/);
  assert.match(pageSource, /補助事業1人当たり給与支給総額の年平均上昇率/);
  assert.doesNotMatch(pageSource, /1人給与成長率|1人給与伸び/);
  assert.match(pageSource, /その他販管費率改善ポイント/);
  assert.match(pageSource, /各期率＋前年差改善pt/);
  assert.match(pageSource, /<strong>\{improvementLabel\}<\/strong><small>当期率/);
  assert.match(pageSource, /actuals-three-year-table/);
  assert.match(pageSource, /content-stack history-actuals-view/);
  assert.match(pageSource, /function roundedInput\(value: number, digits = 2\)/);
  assert.match(pageSource, /上書き内容を反映して再最適化/);
  assert.match(pageSource, /補助事業収支計画（7-1～7-20/);
  assert.match(pageSource, /7-11・7-12・7-15～7-19は第6次Excelと同じ関係式で自動計算/);
  assert.match(pageSource, /2-21～2-36を給与・付加価値・人数・EBITDA/);
  assert.match(pageSource, /step=\{item\.digits === 0 \? 1 : 0\.1\}/);
  assert.match(modelSource, /headcount: Math\.max\(0, Math\.round\(projectHeadcount\)\)/);
  assert.match(reportDataSource, /code: "2-36", label: "EBITDA増加率"/);
  assert.match(pageSource, /15指標・目標へ戻る/);
  assert.match(pageSource, />基準年売上開始<\/button>/);
  assert.match(pageSource, />過去3期入力済み<\/button>/);
  assert.match(pageSource, /createHistoricalOnlySampleProposal/);
  assert.match(sampleProposalSource, /proposal\.drivers = clone\(defaultDrivers\)/);
  assert.match(sampleProposalSource, /delete proposal\.inputValues\?\.\[inputKey\.driver\(key\)\]/);
  assert.match(sampleProposalSource, /delete proposal\.inputValues\?\.\[inputKey\.driverRange\(key, 0\)\]/);
  assert.match(sampleProposalSource, /delete proposal\.inputValues\?\.\[inputKey\.futureCapex\(row\.year\)\]/);
  assert.match(pageSource, /window\.scrollTo\(\{ top: 0, left: 0, behavior: "auto" \}\)/);
  assert.match(pageSource, /function DiagnosticCharts\(\{ plan \}/);
  assert.match(pageSource, /主要指標の推移チャート/);
  assert.match(pageSource, /人員・1人当たり給与/);
  assert.match(pageSource, /労働生産性/);
  assert.match(globalStyles, /\.diagnostic-chart-grid/);
  assert.doesNotMatch(pageSource, /onClick=\{\(\) => setView\(/);
  assert.doesNotMatch(pageSource, /function solveAndOpenAnnualPl\(\)/);
  assert.doesNotMatch(pageSource, /toFixed\(6\)/);
  assert.doesNotMatch(pageSource, /blankableInput/);
  assert.match(pageSource, /inputValues: clone\(inputValues\)/);
  assert.match(pageSource, /event\.target\.value === "" \? null/);
  assert.match(inputValueSource, /A missing key means "not entered"/);
  assert.match(inputValueSource, /else next\[key\] = value/);
  assert.match(proposalSource, /入力データ監査（Null／0区別）/);
  assert.match(pageSource, /metric-group-controls/);
  assert.match(pageSource, /proposal-action-menu/);
  assert.match(pageSource, /document\.addEventListener\("pointerdown", closeProposalMenus\)/);
  assert.match(pageSource, /event\.key !== "Escape"/);
  assert.match(pageSource, /keepOnlyProposalMenuOpen/);
  assert.match(pageSource, />出力 <span aria-hidden="true">▾<\/span>/);
  assert.match(pageSource, />サンプル <span aria-hidden="true">▾<\/span>/);
  assert.doesNotMatch(pageSource, />HTML出力<\/button>/);
  assert.match(globalStyles, /proposal-action-menu-items/);
  assert.match(globalStyles, /grid-template-columns: repeat\(auto-fit, minmax\(230px, 300px\)\)/);
  assert.match(globalStyles, /metric-group-control select \{ width: 100%; max-width: none;/);
  assert.match(pageSource, /に目標設定/);
  assert.match(pageSource, /2指標を同時に最適化/);
  assert.match(pageSource, /最適化結果/);
  assert.match(pageSource, /const \[isSolving, setIsSolving\] = useState\(false\)/);
  assert.match(pageSource, /requestAnimationFrame\(\(\) => setTimeout\(resolve, 0\)\)/);
  assert.match(pageSource, /isSolving \? "計算中…" : "設定した目標に近づける"/);
  assert.match(pageSource, /disabled=\{isSolving\} aria-busy=\{isSolving\}/);
  assert.match(pageSource, /const driverItemCodes = Object\.fromEntries/);
  assert.match(pageSource, /<th>調整項目<small>A～Z<\/small><\/th>/);
  assert.match(pageSource, /className="driver-item-code">\{driverItemCodes\[key\]\}:/);
  assert.match(globalStyles, /\.driver-item-code/);
  assert.match(pageSource, /const round5Benchmarks/);
  assert.match(pageSource, /companySalesCagr: \{ applicant: 20, accepted: 21, statistic: "中央値" \}/);
  assert.match(pageSource, /projectSalesShare: \{ applicant: 80, accepted: 89, statistic: "平均値" \}/);
  assert.match(pageSource, /valueAddedSubsidyRatio: \{ applicant: 171, accepted: 213, statistic: "中央値" \}/);
  assert.match(pageSource, /第5次公式参考値/);
  assert.match(pageSource, /<th>目標値<\/th><th>優先度<\/th><th>判定・未達時の修正候補<\/th>/);
  assert.doesNotMatch(pageSource, /aria-label=\{`\$\{definition\.label\}計画上限`\}/);
  assert.doesNotMatch(pageSource, /<option value="hard">必達<\/option>/);
  assert.match(pageSource, /達成に向けた修正候補/);
  assert.match(pageSource, /の許容上限を.*へ引き上げる/);
  assert.match(pageSource, /の許容下限を.*へ引き下げる/);
  assert.match(pageSource, /slice\(0, 3\)/);
  assert.match(proposalSource, /<th>目標値<\/th><th>判定<\/th>/);
  assert.match(pageSource, /<Round5BenchmarkCell metricKey=\{definition\.key\} unit=\{definition\.unit\} \/>/);
  assert.match(pageSource, /役員関連2指標は第5次に公表値がありません/);
  assert.match(globalStyles, /\.round5-benchmark/);
  assert.match(pageSource, /自動算出/);
  assert.match(pageSource, /個別に目標設定/);
  assert.match(globalStyles, /metric-independent-row/);
  assert.match(globalStyles, /targets-table thead th:nth-child\(2\), \.targets-table td:nth-child\(2\) \{ text-align: left; \}/);
  assert.match(pageSource, /14・15の役員関連2指標は第6次の評価対象外/);
  assert.match(pageSource, /reference-metric-row/);
  assert.match(proposalSource, /参考値・第6次評価対象外/);
  assert.match(pageSource, /同額ペースの\{targetComparisonYears\}年単純換算/);
  assert.match(pageSource, /基準年→事業化報告3年目/);
  assert.match(pageSource, /指標・第6次定義/);
  assert.match(pageSource, /第6次定義：\{definition\.round6Formula\}/);
  assert.match(proposalSource, /指標・第6次定義/);
  assert.match(proposalSource, /item\.round6Formula/);
  assert.doesNotMatch(proposalSource, /目標下限（3年間）/);
  assert.doesNotMatch(pageSource, />両方を制約</);
  assert.match(pageSource, /metricBasisRole\(key, metricGroupBases\) !== "result"/);
  assert.match(metricGroupSource, /companySalesCagr/);
  assert.match(metricGroupSource, /companySalesIncrease/);
  assert.match(metricGroupSource, /type MetricGroupBasis = "rate" \| "amount" \| "both"/);
  assert.match(globalStyles, /actuals-three-year-table \{ overflow-x: hidden; overflow-y: auto; \}/);
  assert.match(pageSource, /申請区分・制度前提/);
  assert.match(pageSource, /className="application-category-copy"/);
  assert.match(pageSource, /制度上の投資額・賃上げ率を自動設定します/);
  assert.match(pageSource, /制度上の必須条件/);
  assert.match(pageSource, /requiredMetricMinimums\(applicationCategory\)/);
  assert.match(applicationRulesSource, /general: "一般企業（100億宣言企業以外）"/);
  assert.match(applicationRulesSource, /defaultApplicationCategory[^=]*= "general"/);
  assert.match(pageSource, /useState<ApplicationCategory>\(defaultApplicationCategory\)/);
  assert.match(pageSource, /proposal\.applicationCategory \?\? defaultApplicationCategory/);
  assert.match(modelSource, /sweep < 10/);
  assert.doesNotMatch(modelSource, /sweep < 4/);
  assert.match(applicationRulesSource, /investmentMinimum: category === "hundredBillion" \? 15 : 20/);
  assert.match(applicationRulesSource, /projectPayCagrMinimum: category === "general" \? 5 : 4\.5/);
  assert.match(applicationRulesSource, /drivers\.subsidy > 50/);
  assert.match(applicationRulesSource, /drivers\.subsidy > drivers\.investment \/ 3/);
  assert.match(pageSource, /driverConstraintFailure\(key, applicationCategory, drivers\)/);
  assert.match(pageSource, /aria-invalid=\{constraintError \? "true" : undefined\}/);
  assert.match(pageSource, /title: "制度上の必須条件に違反"/);
  assert.doesNotMatch(pageSource, /applicationCategory === "startupException"/);
  assert.doesNotMatch(modelSource, /drivers\.investment < 15/);
  assert.match(modelSource, /projectPayGrowthToBase: \[0, 0\.1\]/);
  assert.match(modelSource, /latestPayPerEmployee \/ 1\.02 \*\* yearsBeforeLatest/);
  assert.doesNotMatch(pageSource, /Math\.min\(technicalUpper, Math\.max\(technicalLower, enteredValue\)\)/);
  assert.doesNotMatch(pageSource, /min=\{rangeInputMin\} max=\{rangeInputMax\}/);
  assert.doesNotMatch(pageSource, /技術上限|技術下限|技術的な絶対範囲/);
  assert.match(pageSource, /別の非表示上限は設けません/);
  assert.match(pageSource, /findRequiredBound/);
  assert.match(pageSource, /iteration < 24/);
  assert.match(pageSource, /targetStatus\(definition, probeActual\[definition\.key\], target\)\.ok/);
  assert.match(pageSource, /から少なくとも.*へ引き上げる/);
  assert.match(pageSource, /から少なくとも.*へ引き下げる/);
  assert.match(pageSource, /normalizedInputs = setInputValue\(normalizedInputs, inputKey\.driverRange/);
  assert.match(globalStyles, /\.driver-validation-error/);
  assert.match(globalStyles, /\.statutory-condition/);
  assert.match(globalStyles, /\.application-category-control \{ display: grid; width: min\(100%, 560px\); gap: 8px; \}/);
  assert.match(globalStyles, /\.application-category-copy \{ display: flex; align-items: baseline;/);
  assert.doesNotMatch(html, /codex-preview|react-loading-skeleton/i);
});
