import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);
  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("renders the planning model shell", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);
  const html = await response.text();
  assert.match(html, /<html lang="ja">/i);
  assert.match(html, /<title>成長投資計画シミュレーター（Ver. 大規模成長投資補助金 6次公募）<\/title>/i);
  assert.match(html, /成長投資計画シミュレーター（Ver. 大規模成長投資補助金 6次公募）/);
  assert.match(html, /過去実績と目標値を入力し、補助事業＋その他事業＝全社 の将来PLをシミュレーションします。/);
  assert.doesNotMatch(html, /目標に近づける/);
  assert.match(html, /15指標・目標/);
  const pageSource = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const modelSource = await readFile(new URL("../app/model.ts", import.meta.url), "utf8");
  const inputValueSource = await readFile(new URL("../app/input-values.ts", import.meta.url), "utf8");
  const metricGroupSource = await readFile(new URL("../app/metric-groups.ts", import.meta.url), "utf8");
  const proposalSource = await readFile(new URL("../app/proposal-io.ts", import.meta.url), "utf8");
  const excelMappingSource = await readFile(new URL("../app/excel-mapping.ts", import.meta.url), "utf8");
  const reportDataSource = await readFile(new URL("../app/report-data.ts", import.meta.url), "utf8");
  const sampleProposalSource = await readFile(new URL("../app/sample-proposals.ts", import.meta.url), "utf8");
  const standardWorkflowSource = await readFile(new URL("../scripts/derive-standard-workflow.ts", import.meta.url), "utf8");
  const applicationRulesSource = await readFile(new URL("../app/application-rules.ts", import.meta.url), "utf8");
  const proposalOptimizationSource = await readFile(new URL("../app/proposal-optimization.ts", import.meta.url), "utf8");
  const standaloneBuildSource = await readFile(new URL("../scripts/build-standalone.mjs", import.meta.url), "utf8");
  const globalStyles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  assert.match(pageSource, /<h1 className="product-title">/);
  assert.match(pageSource, /<small>Ver\. 大規模成長投資補助金 6次公募<\/small>/);
  assert.doesNotMatch(pageSource, /第3次定義を比較表示/);
  assert.match(standaloneBuildSource, /成長投資計画シミュレーター_大規模成長投資補助金6次公募\.html/);
  assert.match(standaloneBuildSource, /<title>成長投資計画シミュレーター（Ver\. 大規模成長投資補助金 6次公募）<\/title>/);
  assert.match(standaloneBuildSource, /成長投資計画シミュレーターを読み込んでいます…/);
  assert.doesNotMatch(standaloneBuildSource, /数値設計ラボ/);
  assert.match(globalStyles, /font-size: clamp\(28px, 3vw, 40px\)/);
  const initialInputFunction = pageSource.match(/function createInitialInputValues\(\): InputValues \{[\s\S]*?\n\}/)?.[0] ?? "";
  const suggestionSource = pageSource.match(/const targetAdjustmentSuggestions = useMemo\([\s\S]*?\n  \}, \[adjustedDrivers,[\s\S]*?\]\);/)?.[0] ?? "";
  assert.match(globalStyles, /\.tabs \{ position: sticky; top: 0; z-index: 25;/);
  assert.match(pageSource, /className="official-section-heading"/);
  assert.match(pageSource, /label="損益計算書" range="2-1～2-20"/);
  assert.match(pageSource, /label="P\/L関連計算項目" range="2-21～2-36"/);
  assert.match(globalStyles, /\.official-section-heading th, \.official-section-heading td \{ position: sticky; top: 56px;/);
  assert.match(globalStyles, /\.table-panel \{ overflow: visible;/);
  assert.match(globalStyles, /\.table-panel > \.panel-heading \{ position: sticky; top: 46px; z-index: 18;/);
  assert.match(globalStyles, /\.manual-sections > div > h3 \{ position: sticky; top: 46px; z-index: 18;/);
  assert.match(globalStyles, /\.diagnostic-panel > h3 \{ position: sticky; top: 46px; z-index: 18;/);
  assert.match(globalStyles, /\.wide-table, \.targets-table-wrap \{[^}]*overflow-x: auto; overflow-y: visible;/);
  assert.match(globalStyles, /\.balance-sheet-table \{[^}]*overflow-x: auto; overflow-y: visible;/);
  assert.match(globalStyles, /\.table-panel:has\(> \.manual-sections\) > \.panel-heading \{ position: static;/);
  assert.match(globalStyles, /\.page-sticky-header-overlay \{ position: fixed; z-index: 17; overflow: hidden;/);
  assert.match(globalStyles, /\.page-sticky-header-overlay thead th:first-child \{ position: sticky; left: 0;/);
  assert.match(globalStyles, /\.floating-table-scrollbar \{ position: fixed; bottom: 0; z-index: 24; display: none;/);
  assert.match(globalStyles, /\.floating-table-scrollbar\.is-visible \{ display: block;/);
  assert.match(globalStyles, /\.data-io-view \.proposal-action-menu-items \{ right: auto; left: 0;/);
  assert.match(globalStyles, /\.data-io-view \.proposal-filebar:has\(\.proposal-action-menu\[open\]\) \{ padding-bottom: 140px;/);
  assert.doesNotMatch(globalStyles, /max-height: min\(76vh, 860px\)/);
  assert.match(pageSource, /function usePageStickyTableHeaders\(\)/);
  assert.match(pageSource, /function useFloatingHorizontalTableScrollbar\(\)/);
  assert.match(pageSource, /activeWrapper\.scrollLeft = scrollbar\.scrollLeft/);
  assert.match(pageSource, /rect\.bottom > window\.innerHeight/);
  assert.match(pageSource, /overlay\.style\.top = `\$\{Math\.min\(targetTop, wrapperRect\.bottom - headerHeight\)\}px`/);
  assert.doesNotMatch(pageSource, /page-sticky-header-offset/);
  assert.match(pageSource, /type View = [^;]*"io"/);
  assert.match(pageSource, /goToView\("io"\)\}>データ入出力<\/button>/);
  assert.equal(pageSource.match(/className="tab-group-separator" aria-hidden="true">\|<\/span>/g)?.length, 2);
  assert.match(globalStyles, /\.tab-group-separator \{/);
  assert.match(pageSource, /\{view === "io" && \(/);
  assert.ok(pageSource.indexOf('<nav className="tabs"') < pageSource.indexOf('<section className="proposal-filebar"'));
  assert.match(pageSource, /className="sample-library-panel"/);
  assert.match(pageSource, /SAMPLE LIBRARY/);
  assert.doesNotMatch(pageSource, /<summary>サンプル/);
  assert.ok(pageSource.indexOf('className="excel-mapping-panel"') < pageSource.indexOf('className="sample-library-panel"'));
  assert.match(pageSource, /すでに入力されているデータがあります。サンプルを読み込むと、現在の入力・設定・最適化結果を上書きします。よろしいですか？/);
  assert.match(pageSource, /if \(!confirmSampleReplacement\(\)\) return;/);
  assert.match(globalStyles, /\.data-io-grid \{ display: grid; grid-template-columns: 1fr;/);
  assert.match(globalStyles, /\.sample-library-grid \{ display: grid; grid-template-columns: repeat\(2,/);
  assert.match(pageSource, /任意形式のExcelと入出力する/);
  assert.match(pageSource, /取込内容を確認/);
  assert.match(pageSource, /別Excelとして出力/);
  assert.match(pageSource, /確認した値を反映/);
  assert.match(pageSource, /定義書作成マニュアル/);
  assert.match(pageSource, /Copilot指示をコピー/);
  assert.match(pageSource, /navigator\.clipboard\?\.writeText/);
  assert.match(excelMappingSource, /growth-investment-excel-mapping\/v1/);
  assert.match(excelMappingSource, /EXCEL_MAPPING_COPILOT_PROMPT/);
  assert.match(excelMappingSource, /空欄と0は区別/);
  assert.match(excelMappingSource, /数式セルです。入力セルを指定してください/);
  assert.match(standaloneBuildSource, /excel-mapping\.ts/);
  assert.match(globalStyles, /\.excel-mapping-steps \{ display: grid; grid-template-columns: repeat\(3,/);
  assert.doesNotMatch(initialInputFunction, /driverRange/);
  assert.match(pageSource, /forecastSettingsStarted/);
  assert.match(pageSource, /forecastSettingsReady/);
  assert.match(pageSource, /将来予測の水準が指定済みです。過去データを基にした推奨値に変更してよろしいですか？/);
  assert.match(pageSource, /将来予測・調整水準が未設定です。/);
  assert.match(pageSource, /設定した目標に近づける/);
  assert.match(pageSource, /projectSalesGrowth: \{ initial: 0\.22, lower: 0\.15, upper: 0\.30 \}/);
  assert.match(pageSource, /その他事業｜設備導入期間/);
  assert.match(pageSource, /その他事業｜基準年後/);
  assert.match(pageSource, /applyOtherSynergyLift\("otherSalesGrowth", "otherSalesGrowthToBase", 0\.02\)/);
  assert.match(pageSource, /設備導入期間＋2\.0pt/);
  assert.match(pageSource, /補助事業とのシナジーを見込み/);
  assert.match(pageSource, /projectPayGrowth: \{ initial: 0\.07, lower: 0\.05, upper: 0\.10 \}/);
  assert.match(pageSource, /benchmark && key !== "projectOfficerPayGrowth"/);
  assert.doesNotMatch(pageSource, /nextDrivers\.projectOfficerPayGrowth = nextDrivers\.projectPayGrowth/);
  assert.doesNotMatch(pageSource, /nextDrivers\.projectOfficerPayGrowthToBase = nextDrivers\.projectPayGrowthToBase/);
  assert.match(pageSource, /過去3期の役員1人当たり給与から推計/);
  assert.match(pageSource, /projectCogsImprovementAfterBase: \{ initial: 0\.015, lower: 0, upper: 0\.03 \}/);
  assert.match(pageSource, /設備導入期間0～2pt、基準年後0～3pt/);
  assert.match(pageSource, /const improvementDriverKeys/);
  assert.match(pageSource, /"investment", "subsidy", "usefulLife"/);
  assert.match(pageSource, /keys: \["projectMarketGrowth"\]/);
  assert.match(pageSource, /ローカルベンチマーク固定値/);
  assert.match(pageSource, /固定入力・判定対象外/);
  assert.match(pageSource, /key === "investment" \|\| key === "subsidy" \|\| key === "usefulLife" \|\| key === "projectMarketGrowth"/);
  assert.match(pageSource, /市場伸び率・補助事業投資額・申請補助金額・耐用年数は固定入力/);
  assert.match(proposalSource, /\["investment", "subsidy", "usefulLife", "projectMarketGrowth"\]\.includes\(key\) \? undefined/);
  assert.match(pageSource, /calculateScaleDependentTargetDefaults/);
  assert.match(pageSource, /15指標の増加額5項目は固定中央値を使わず/);
  assert.match(pageSource, /デフォルト設定後に算出/);
  assert.doesNotMatch(pageSource, /原価率改善 1\.5pt［-2～5pt］/);
  assert.match(pageSource, /5ji_median\.pdf/);
  assert.match(pageSource, /補助事業1人当たり給与支給総額の年平均上昇率/);
  assert.doesNotMatch(pageSource, /1人給与成長率|1人給与伸び/);
  assert.match(pageSource, /その他販管費率改善ポイント/);
  assert.match(pageSource, /各期率＋前年差改善pt/);
  assert.match(pageSource, /<strong>\{improvementLabel\}<\/strong><small>当期率/);
  assert.match(pageSource, /actuals-three-year-table/);
  assert.match(pageSource, /content-stack history-actuals-view/);
  assert.match(pageSource, /function roundedInput\(value: number, digits = 2\)/);
  assert.match(pageSource, /上書き内容を反映して再最適化/);
  assert.match(pageSource, /補助事業収支計画（7-1～7-20/);
  assert.match(pageSource, /7-11・7-12・7-15～7-19は第6次Excelと同じ関係式で自動計算/);
  assert.match(pageSource, /2-21～2-36を給与・付加価値・人数・EBITDA/);
  assert.match(pageSource, /うち役員の人件費（自動計算）/);
  assert.match(pageSource, /うち従業員の人件費（自動計算）/);
  assert.match(pageSource, /employeeSalary: next, employeePay: nextPay/);
  assert.match(pageSource, /officerBonus: next, officerPay: nextPay/);
  assert.match(pageSource, /researchDevelopment: next/);
  assert.match(modelSource, /segment\.employeeSalary \?\? segment\.employeePay/);
  assert.match(modelSource, /segment\.sgaDepreciation \?\? segment\.depreciation/);
  assert.match(pageSource, /step=\{item\.digits === 0 \? 1 : 0\.1\}/);
  assert.match(modelSource, /headcount: Math\.max\(0, Math\.round\(projectHeadcount\)\)/);
  assert.match(reportDataSource, /code: "2-36", label: "EBITDA増加率"/);
  assert.match(pageSource, /15指標・目標へ戻る/);
  assert.match(pageSource, />基準年売上開始ケース（過去3期入力済み）<\/button>/);
  assert.match(pageSource, />標準ケース（過去3期入力済み）<\/button>/);
  assert.match(pageSource, /createHistoricalOnlySampleProposal/);
  assert.match(pageSource, /createBaseYearLaunchHistoricalOnlySampleProposal/);
  assert.match(sampleProposalSource, /基準年売上開始・過去3期入力済みサンプル/);
  assert.match(sampleProposalSource, /proposal\.drivers = clone\(defaultDrivers\)/);
  assert.match(sampleProposalSource, /delete proposal\.inputValues\?\.\[inputKey\.driver\(key\)\]/);
  assert.match(sampleProposalSource, /delete proposal\.inputValues\?\.\[inputKey\.driverRange\(key, 0\)\]/);
  assert.match(sampleProposalSource, /delete proposal\.inputValues\?\.\[inputKey\.futureCapex\(row\.year\)\]/);
  assert.match(pageSource, /window\.scrollTo\(\{ top: 0, left: 0, behavior: "auto" \}\)/);
  assert.match(pageSource, /← 将来データ入力に戻る/);
  assert.match(pageSource, /診断タブに進む →/);
  assert.match(pageSource, /投資計画 計画値/);
  assert.doesNotMatch(pageSource, /第6次定義：計画値/);
  assert.match(pageSource, /function DiagnosticCharts\(\{ plan \}/);
  assert.match(pageSource, /主要指標の推移チャート/);
  assert.match(pageSource, /人員・1人当たり給与/);
  assert.match(pageSource, /労働生産性/);
  assert.match(globalStyles, /\.diagnostic-chart-grid/);
  assert.doesNotMatch(pageSource, /onClick=\{\(\) => setView\(/);
  assert.doesNotMatch(pageSource, /function solveAndOpenAnnualPl\(\)/);
  assert.doesNotMatch(pageSource, /toFixed\(6\)/);
  assert.doesNotMatch(pageSource, /blankableInput/);
  assert.match(pageSource, /inputValues: clone\(inputValues\)/);
  assert.match(pageSource, /event\.target\.value === "" \? null/);
  assert.match(inputValueSource, /A missing key means "not entered"/);
  assert.match(inputValueSource, /else next\[key\] = value/);
  assert.match(proposalSource, /入力データ監査（Null／0区別）/);
  assert.match(pageSource, /metric-group-controls/);
  assert.match(pageSource, /proposal-action-menu/);
  assert.match(pageSource, /document\.addEventListener\("pointerdown", closeProposalMenus\)/);
  assert.match(pageSource, /event\.key !== "Escape"/);
  assert.match(pageSource, /keepOnlyProposalMenuOpen/);
  assert.match(pageSource, />出力 <span aria-hidden="true">▾<\/span>/);
  assert.doesNotMatch(pageSource, />サンプル <span aria-hidden="true">▾<\/span>/);
  assert.match(pageSource, /<button onClick=\{loadHistoricalOnlySample\}>標準ケース/);
  assert.match(pageSource, /<button className="sample-result-button" onClick=\{loadSampleProposal\}>最適化済み標準提案/);
  assert.doesNotMatch(pageSource, />HTML出力<\/button>/);
  assert.match(globalStyles, /proposal-action-menu-items/);
  assert.match(globalStyles, /grid-template-columns: repeat\(auto-fit, minmax\(230px, 300px\)\)/);
  assert.match(globalStyles, /metric-group-control select \{ width: 100%; max-width: none;/);
  assert.match(pageSource, /に目標設定/);
  assert.match(pageSource, /2指標を同時に最適化/);
  assert.match(pageSource, /最適化結果/);
  assert.match(pageSource, /const \[isSolving, setIsSolving\] = useState\(false\)/);
  assert.match(pageSource, /requestAnimationFrame\(\(\) => setTimeout\(resolve, 0\)\)/);
  assert.match(pageSource, /isSolving \? "計算中…" : "設定した目標に近づける"/);
  assert.match(pageSource, /disabled=\{isSolving\} aria-busy=\{isSolving\}/);
  assert.match(pageSource, /const driverItemCodes = Object\.fromEntries/);
  assert.match(pageSource, /<th>調整項目<small>A～Z<\/small><\/th>/);
  assert.match(pageSource, /className="driver-item-code">\{driverItemCodes\[key\]\}:/);
  assert.match(globalStyles, /\.driver-item-code/);
  assert.match(pageSource, /const round5Benchmarks/);
  assert.match(pageSource, /companySalesCagr: \{ applicant: 20, accepted: 21, statistic: "中央値" \}/);
  assert.match(pageSource, /projectSalesShare: \{ applicant: 80, accepted: 89, statistic: "平均値" \}/);
  assert.match(pageSource, /valueAddedSubsidyRatio: \{ applicant: 171, accepted: 213, statistic: "中央値" \}/);
  assert.match(pageSource, /第5次公式参考値/);
  assert.match(pageSource, /<th>目標値<\/th><th>優先度<\/th><th>判定・未達時の修正候補<\/th>/);
  assert.doesNotMatch(pageSource, /aria-label=\{`\$\{definition\.label\}計画上限`\}/);
  assert.doesNotMatch(pageSource, /<option value="hard">必達<\/option>/);
  assert.match(pageSource, /達成に向けた修正候補/);
  assert.match(pageSource, /の許容上限を.*へ引き上げる/);
  assert.match(pageSource, /の許容下限を.*へ引き下げる/);
  assert.match(pageSource, /type DriverRangeSuggestion =/);
  assert.match(pageSource, /projectSalesGrowthToBase: \{ label: "補助事業 売上成長率（設備導入期間）"/);
  assert.match(pageSource, /projectSalesGrowth: \{ label: "補助事業 売上成長率（基準年→事業化報告3年目）"/);
  assert.match(pageSource, /otherSalesGrowthToBase: \{ label: "その他事業 売上成長率（最新決算期→基準年）"/);
  assert.match(pageSource, /const improvesTargetGap = \(probeValue: number\)/);
  assert.match(suggestionSource, /for \(const key of adjustableDriverKeys\)/);
  assert.doesNotMatch(suggestionSource, /projectPayGrowthToBase|otherPayGrowthToBase/);
  assert.match(pageSource, /basisRole !== "result" && adjustedPlan && targetSet && !status\.ok/);
  assert.doesNotMatch(pageSource, /Math\.abs\(current - rangeUpper\)/);
  assert.match(pageSource, /function applySelectedDriverRangeSuggestions\(metricKey: MetricKey, suggestions: DriverRangeSuggestion\[\]\)/);
  assert.match(pageSource, /type="checkbox" checked=\{Boolean\(selectedAdjustmentSuggestions/);
  assert.match(pageSource, />選択した候補を一括適用<\/button>/);
  assert.match(globalStyles, /\.apply-selected-suggestions/);
  assert.match(pageSource, /className="driver-group-heading"[\s\S]*?<th><strong>\{group\.label\}<\/strong>/);
  assert.match(pageSource, /<td aria-hidden="true" colSpan=\{historicalPlan\.length \+ 4\}><\/td>/);
  assert.match(globalStyles, /\.driver-target-table \.driver-group-heading th \{ position: sticky; left: 0;/);
  assert.match(globalStyles, /\.driver-target-table \.driver-group-heading th, \.driver-target-table \.driver-group-heading td \{[^}]*background: #e2ece6;[^}]*color: #28483a;/);
  assert.match(globalStyles, /\.driver-target-table tr\.driver-adjustable th:first-child \{ background: #fcf8ed; \}/);
  assert.match(pageSource, /slice\(0, 3\)/);
  assert.match(proposalSource, /<th>目標値<\/th><th>判定<\/th>/);
  assert.match(pageSource, /<Round5BenchmarkCell metricKey=\{definition\.key\} unit=\{definition\.unit\} \/>/);
  assert.match(pageSource, /役員関連2指標は第5次に公表値がありません/);
  assert.match(globalStyles, /\.round5-benchmark/);
  assert.match(pageSource, /自動算出/);
  assert.match(pageSource, /個別に目標設定/);
  assert.match(globalStyles, /metric-independent-row/);
  assert.match(globalStyles, /targets-table thead th:nth-child\(2\), \.targets-table td:nth-child\(2\) \{ position: sticky; left: 44px;/);
  assert.match(globalStyles, /targets-table tr\.metric-basis-row td:nth-child\(-n\+2\).*background: #f4f8f2/);
  assert.match(pageSource, /historicalPlan\.slice\(1\)\.map\(\(row\) => <th key=\{row\.year\}>/);
  assert.match(globalStyles, /\.targets-table th:nth-child\(7\), \.targets-table td:nth-child\(7\) \{ width: 145px; min-width: 145px; max-width: 145px; white-space: normal;/);
  assert.match(globalStyles, /\.targets-table \{ width: max\(100%, 1400px\) !important; table-layout: fixed; \}/);
  assert.match(globalStyles, /\.targets-table th:nth-child\(10\), \.targets-table td:nth-child\(10\), \.target-judgement \{ width: 250px; min-width: 250px; max-width: 250px; \}/);
  assert.match(pageSource, /14・15の役員関連2指標は第6次の評価対象外/);
  assert.match(pageSource, /reference-metric-row/);
  assert.match(proposalSource, /参考値・第6次評価対象外/);
  assert.match(pageSource, /同額ペースの\{targetComparisonYears\}年単純換算/);
  assert.match(pageSource, /基準年→事業化報告3年目/);
  assert.match(pageSource, /指標・第6次定義/);
  assert.match(pageSource, /第6次定義：\{definition\.round6Formula\}/);
  assert.match(proposalSource, /指標・第6次定義/);
  assert.match(proposalSource, /item\.round6Formula/);
  assert.doesNotMatch(proposalSource, /目標下限（3年間）/);
  assert.doesNotMatch(pageSource, />両方を制約</);
  assert.match(proposalOptimizationSource, /metricBasisRole\(key, metricGroupBases\) !== "result"/);
  assert.match(metricGroupSource, /companySalesCagr/);
  assert.match(metricGroupSource, /companySalesIncrease/);
  assert.match(metricGroupSource, /type MetricGroupBasis = "rate" \| "amount" \| "both"/);
  assert.match(globalStyles, /actuals-three-year-table \{ overflow-x: hidden; overflow-y: visible; \}/);
  assert.match(pageSource, /申請区分・制度前提/);
  assert.match(pageSource, /className="application-category-copy"/);
  assert.match(pageSource, /制度上の投資額・賃上げ率を自動設定します/);
  assert.match(pageSource, /制度上の必須条件/);
  assert.match(pageSource, /runPlanningOptimization/);
  assert.match(proposalOptimizationSource, /requiredMetricMinimums\(applicationCategory\)/);
  assert.match(applicationRulesSource, /general: "一般企業（100億宣言企業以外）"/);
  assert.match(applicationRulesSource, /defaultApplicationCategory[^=]*= "general"/);
  assert.match(pageSource, /useState<ApplicationCategory>\(defaultApplicationCategory\)/);
  assert.match(pageSource, /proposal\.applicationCategory \?\? defaultApplicationCategory/);
  assert.match(modelSource, /sweep < 10/);
  assert.doesNotMatch(modelSource, /sweep < 4/);
  assert.match(applicationRulesSource, /investmentMinimum: category === "hundredBillion" \? 15 : 20/);
  assert.match(applicationRulesSource, /projectPayCagrMinimum: category === "general" \? 5 : 4\.5/);
  assert.match(applicationRulesSource, /drivers\.subsidy > 50/);
  assert.match(applicationRulesSource, /maximumSubsidyAmount\(drivers\.investment\)/);
  assert.match(applicationRulesSource, /Math\.floor\(\(exactMaximum \+ Number\.EPSILON\) \* 100\) \/ 100/);
  assert.match(pageSource, /driverConstraintFailure\(key, applicationCategory, drivers\)/);
  assert.match(pageSource, /proposal\.adjustedDrivers/);
  assert.match(pageSource, /setAdjustedDrivers\(importedAdjustedDrivers\)/);
  assert.match(pageSource, /historicalPlan\.slice\(1\)\.map/);
  assert.match(pageSource, /history\.values\.slice\(1\)\.map/);
  assert.match(globalStyles, /\.driver-target-table table \{ width: max-content !important; min-width: 1220px !important; \}/);
  assert.match(globalStyles, /\.driver-target-table table \{ width: max\(100%, 1220px\) !important; table-layout: fixed; \}/);
  assert.match(globalStyles, /\.driver-target-table tbody tr:not\(\.driver-group-heading\) th:first-child \{ white-space: normal; overflow-wrap: anywhere; line-height: 1\.45; \}/);
  assert.match(pageSource, />使い方を試す<\/strong>/);
  assert.match(pageSource, />シミュレーション結果を見る<\/strong>/);
  assert.match(pageSource, />最適化済み標準提案<\/button>/);
  assert.match(pageSource, />一部目標未達ケース<\/button>/);
  assert.match(sampleProposalSource, /createPartiallyUnmetSampleProposal/);
  assert.match(sampleProposalSource, /inputKey\.target\("companyPaySchedule", "value"\)\] = 3\.5/);
  assert.match(sampleProposalSource, /proposal\.adjustedDrivers = clone\(partiallyUnmetAdjustedDrivers\)/);
  assert.match(sampleProposalSource, /reoptimizeSampleProposal/);
  assert.match(globalStyles, /\.sample-menu-section \+ \.sample-menu-section/);
  assert.doesNotMatch(globalStyles, /\.sample-menu-section \.sample-result-button \{ background: var\(--green-soft\);/);
  assert.match(standardWorkflowSource, /const initialPlanWithInputs = applyOverrides\(initialPlan\)/);
  assert.match(standardWorkflowSource, /const second = optimizeDrivers\(\s*initialDrivers,/);
  assert.match(pageSource, /aria-invalid=\{constraintError \? "true" : undefined\}/);
  assert.match(pageSource, /title: "制度上の必須条件に違反"/);
  assert.doesNotMatch(pageSource, /applicationCategory === "startupException"/);
  assert.doesNotMatch(modelSource, /drivers\.investment < 15/);
  assert.match(modelSource, /projectPayGrowthToBase: \[0, 0\.1\]/);
  assert.match(modelSource, /latestPayPerEmployee \/ 1\.02 \*\* yearsBeforeLatest/);
  assert.doesNotMatch(pageSource, /Math\.min\(technicalUpper, Math\.max\(technicalLower, enteredValue\)\)/);
  assert.doesNotMatch(pageSource, /min=\{rangeInputMin\} max=\{rangeInputMax\}/);
  assert.doesNotMatch(pageSource, /技術上限|技術下限|技術的な絶対範囲/);
  assert.match(pageSource, /別の非表示上限は設けません/);
  assert.match(pageSource, /findRequiredBound/);
  assert.match(pageSource, /iteration < 24/);
  assert.match(pageSource, /targetStatus\(definition, probeActual\[definition\.key\], target\)\.ok/);
  assert.match(pageSource, /から少なくとも.*へ引き上げる/);
  assert.match(pageSource, /から少なくとも.*へ引き下げる/);
  assert.match(pageSource, /normalizedInputs = setInputValue\(normalizedInputs, inputKey\.driverRange/);
  assert.match(globalStyles, /\.driver-validation-error/);
  assert.match(globalStyles, /\.statutory-condition/);
  assert.match(globalStyles, /\.application-category-control \{ display: grid; width: min\(100%, 560px\); gap: 8px; \}/);
  assert.match(globalStyles, /\.application-category-copy \{ display: flex; align-items: baseline;/);
  assert.doesNotMatch(html, /codex-preview|react-loading-skeleton/i);
});
