import type { ReactNode } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { NumberInput } from '../../components/ui/number-input';
import { Textarea } from '../../components/ui/textarea';
import { inferMetricPeriodKind, validateMetricDefinition } from '../../domain/metrics';
import { resolveTimeline } from '../../domain/timeline';
import type { ManagementMetricDefinition, MetricTimeAnchor, ProgramConfiguration } from '../../domain/types';
import { useModelStore } from '../../store/model-store-context';
import { ProgramFileMenu } from './ProgramFileMenu';
import { addPeriodDefinition, removePeriodDefinition, removeSpecialYearDefinition, renameNumericDefinition } from '../../domain/program-editor';

const fieldClass = 'grid gap-1 text-[10px] font-bold text-muted-foreground';
const selectClass = 'h-9 rounded-md border border-input bg-surface px-2 text-sm text-ink';

function nextId(prefix: string, count: number) { return `${prefix}-${count + 1}-${Date.now().toString(36)}`; }
function nextPointId(points: ManagementMetricDefinition['timePoints']) {
  const used = new Set(points.map((point) => point.id));
  return 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').find((id) => !used.has(id)) ?? `P${points.length + 1}`;
}
function encodeAnchor(anchor: MetricTimeAnchor) {
  if (anchor.type === 'historicalEnd') return 'historicalEnd';
  if (anchor.type === 'specialYear') return `specialYear:${anchor.specialYearId}`;
  return `${anchor.type}:${anchor.periodId}`;
}
function decodeAnchor(value: string): MetricTimeAnchor {
  const [type, id] = value.split(':');
  if (type === 'historicalEnd') return { type: 'historicalEnd' };
  if (type === 'specialYear') return { type, specialYearId: id };
  return { type: type as 'periodStart' | 'periodEnd', periodId: id };
}

function DefinitionSectionHeader({ id, title, description, addLabel, onAdd }: { id: string; title: string; description?: ReactNode; addLabel: string; onAdd: () => void }) {
  return <div data-testid={`definition-section-header-${id}`} className="sticky top-12 z-30 flex min-h-12 items-center justify-between gap-4 border-b border-line bg-surface py-2 shadow-sm"><div><h3 className="m-0 text-base font-bold">{title}</h3>{description && <p className="mt-1 mb-0 text-xs text-muted-foreground">{description}</p>}</div><Button variant="outline" size="sm" aria-label={addLabel} onClick={onAdd}><Plus />追加</Button></div>;
}

function MetricCard({ metric, program, update, remove }: { metric: ManagementMetricDefinition; program: ProgramConfiguration; update: (metric: ManagementMetricDefinition) => void; remove: () => void }) {
  let warning = '';
  try { validateMetricDefinition(metric); } catch (cause) { warning = cause instanceof Error ? cause.message : '指標定義が不正です'; }
  const addPoint = () => update({ ...metric, timePoints: [...metric.timePoints, { id: nextPointId(metric.timePoints), anchor: { type: 'periodEnd', periodId: program.definitions.periods.at(-1)?.id ?? 'historical' }, offset: 0 }] });
  return <article data-testid={`metric-${metric.id}`} className={`border-t-[3px] border-navy bg-background p-4 ${metric.enabled ? '' : 'opacity-45'}`}>
    <div className="mb-3 flex items-center justify-between gap-3"><div><span className="text-[10px] font-bold text-teal">{inferMetricPeriodKind(metric)}</span><h4 className="m-0 text-base font-bold">{metric.label}</h4></div><div className="flex items-center gap-2"><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={metric.enabled} onChange={(event) => update({ ...metric, enabled: event.target.checked })} />使用する</label><Button variant="ghost" size="icon" aria-label={`${metric.label}を削除`} onClick={remove}><Trash2 /></Button></div></div>
    <div className="grid grid-cols-[1.4fr_.8fr_.7fr_.7fr] gap-2">
      <label className={fieldClass}>指標名<Input value={metric.label} onChange={(event) => update({ ...metric, label: event.target.value })} /></label>
      <label className={fieldClass}>対象範囲<select className={selectClass} value={metric.scope} onChange={(event) => update({ ...metric, scope: event.target.value as ManagementMetricDefinition['scope'] })}><option value="company">全社</option><option value="base">ベース事業</option><option value="subsidy">補助事業</option></select></label>
      <label className={fieldClass}>目標値<NumberInput value={metric.target} onValueChange={(value) => update({ ...metric, target: value })} /></label>
      <label className={fieldClass}>判定<select className={selectClass} value={metric.direction} onChange={(event) => update({ ...metric, direction: event.target.value as 'min' | 'max' })}><option value="min">以上</option><option value="max">以下</option></select></label>
    </div>
    <div className="mt-3 grid gap-2"><div className="flex items-center justify-between"><strong className="text-xs">使用時点</strong><Button variant="outline" size="sm" aria-label={`${metric.label}の時点を追加`} onClick={addPoint}><Plus />時点を追加</Button></div>{metric.timePoints.map((point, index) => <div key={`${point.id}-${index}`} className="grid grid-cols-[42px_1fr_130px_36px] items-end gap-2 rounded-md border border-line bg-surface p-2"><strong className="self-center text-lg text-teal">{point.id}</strong><label className={fieldClass}>基準時点<select className={selectClass} value={encodeAnchor(point.anchor)} onChange={(event) => update({ ...metric, timePoints: metric.timePoints.map((candidate) => candidate === point ? { ...candidate, anchor: decodeAnchor(event.target.value) } : candidate) })}><option value="historicalEnd">過去実績・終了年</option>{program.definitions.specialYears.map((year) => <option key={year.id} value={`specialYear:${year.id}`}>{year.label}</option>)}{program.definitions.periods.flatMap((period) => [<option key={`${period.id}-start`} value={`periodStart:${period.id}`}>{period.label}・開始年</option>, <option key={`${period.id}-end`} value={`periodEnd:${period.id}`}>{period.label}・終了年</option>])}</select></label><label className={fieldClass}>調整年数<NumberInput value={point.offset} onValueChange={(value) => update({ ...metric, timePoints: metric.timePoints.map((candidate) => candidate === point ? { ...candidate, offset: value } : candidate) })} /></label><Button variant="ghost" size="icon" disabled={metric.timePoints.length <= 1} aria-label={`${metric.label}の時点${point.id}を削除`} onClick={() => update({ ...metric, timePoints: metric.timePoints.filter((candidate) => candidate !== point) })}><Trash2 /></Button></div>)}</div>
    <label className={`${fieldClass} mt-3`}>計算式<Textarea value={metric.formula} onChange={(event) => update({ ...metric, formula: event.target.value })} /></label>
    {warning && <p role="alert" className="mt-1 text-[10px] font-bold text-orange">{warning}</p>}
    <div className="mt-2 grid grid-cols-3 gap-2"><label className={fieldClass}>出力単位<Input value={metric.outputUnit} onChange={(event) => update({ ...metric, outputUnit: event.target.value })} /></label><label className={fieldClass}>個社目標の扱い<select aria-label={`${metric.label} 個社目標の扱い`} className={selectClass} value={metric.targetPolicy ?? 'reference'} onChange={(event) => update({ ...metric, targetPolicy: event.target.value as NonNullable<ManagementMetricDefinition['targetPolicy']> })}><option value="reference">個社目標を優先</option><option value="minimum">制度目標以上</option><option value="maximum">制度目標以下</option></select></label><label className={fieldClass}>最適化<select className={selectClass} value={metric.optimization} onChange={(event) => update({ ...metric, optimization: event.target.value as 'adjustable' | 'fixed' })}><option value="adjustable">最適化で変化</option><option value="fixed">目標最適化で変化しない</option></select></label></div>
  </article>;
}

export function DefinitionPage() {
  const program = useModelStore((state) => state.program);
  const replaceProgram = useModelStore((state) => state.replaceProgram);
  const timeline = resolveTimeline(program);
  const change = (mutate: (draft: ProgramConfiguration) => void) => { const draft = structuredClone(program); mutate(draft); replaceProgram(draft); };
  const addPeriod = () => replaceProgram(addPeriodDefinition(program));
  const addSpecialYear = () => change((draft) => draft.definitions.specialYears.push({ id: nextId('special', draft.definitions.specialYears.length), label: `特別年${draft.definitions.specialYears.length + 1}`, anchor: { type: 'historicalEnd' }, offset: 0 }));
  return <main className="mt-3 grid gap-3">
    <section className="flex items-start justify-between gap-5 border border-line bg-surface p-6"><div className="flex-1"><span className="text-[10px] font-extrabold tracking-[.08em] text-orange">制度・プロジェクト共通</span><Input aria-label="制度名" className="mt-2 max-w-xl text-lg font-bold" value={program.program.name} onChange={(event) => change((draft) => { draft.program.name = event.target.value; })} /><p className="mb-0 text-sm text-muted-foreground">区間・特別年・数値・経営指標を制度定義ファイルとして定義します。個社ごとに変わる実年は次画面で設定します。</p></div><ProgramFileMenu /></section>
    <section className="grid grid-cols-2 gap-4 border border-line bg-surface p-5"><div className="relative isolate"><DefinitionSectionHeader id="periods" title="区間名の定義" addLabel="区間を追加" onAdd={addPeriod} /><div className="grid gap-2"><article className="grid grid-cols-[1fr_110px] items-center gap-2 border-t border-line p-2"><Input aria-label="過去実績区間 名称" value={program.definitions.historical.label} onChange={(event) => change((draft) => { draft.definitions.historical.label = event.target.value; })} /><small>固定・削除不可</small></article>{program.definitions.periods.map((period, index) => <article key={period.id} className="grid grid-cols-[1fr_130px_36px] items-center gap-2 border-t border-line p-2"><Input aria-label={`区間${index + 1} 名称`} value={period.label} onChange={(event) => change((draft) => { draft.definitions.periods[index].label = event.target.value; })} /><select className={selectClass} value={period.modelPhase} onChange={(event) => change((draft) => { draft.definitions.periods[index].modelPhase = event.target.value as 'toBase' | 'postBase'; })}><option value="toBase">基準年まで</option><option value="postBase">基準年後</option></select><Button variant="ghost" size="icon" disabled={program.definitions.periods.length <= 1} aria-label={`${period.label}を削除`} onClick={() => replaceProgram(removePeriodDefinition(program, period.id))}><Trash2 /></Button></article>)}</div></div>
      <div className="relative isolate"><DefinitionSectionHeader id="special-years" title="特別年の呼称" addLabel="特別年を追加" onAdd={addSpecialYear} /><div className="grid gap-2">{program.definitions.specialYears.map((year, index) => <article key={year.id} className="grid grid-cols-[1fr_1fr_100px_36px] items-end gap-2 border-t border-line p-2"><label className={fieldClass}>呼称<Input aria-label={`特別年${index + 1} 呼称`} value={year.label} onChange={(event) => change((draft) => { draft.definitions.specialYears[index].label = event.target.value; })} /></label><label className={fieldClass}>基準期間<select className={selectClass} value={year.anchor.type === 'historicalEnd' ? 'historicalEnd' : `${year.anchor.type}:${year.anchor.periodId}`} onChange={(event) => change((draft) => { const [type, periodId] = event.target.value.split(':'); draft.definitions.specialYears[index].anchor = type === 'historicalEnd' ? { type: 'historicalEnd' } : { type: type as 'periodStart' | 'periodEnd', periodId }; })}><option value="historicalEnd">過去実績・終了年</option>{program.definitions.periods.flatMap((period) => [<option key={`${period.id}-s`} value={`periodStart:${period.id}`}>{period.label}・開始年</option>, <option key={`${period.id}-e`} value={`periodEnd:${period.id}`}>{period.label}・終了年</option>])}</select></label><label className={fieldClass}>調整年数<NumberInput aria-label={`特別年${index + 1} 調整年数`} value={year.offset} onValueChange={(value) => change((draft) => { draft.definitions.specialYears[index].offset = value; })} /></label><Button variant="ghost" size="icon" aria-label={`${year.label}を削除`} onClick={() => replaceProgram(removeSpecialYearDefinition(program, year.id))}><Trash2 /></Button></article>)}</div><p className="text-[10px] text-muted-foreground">現在の解決年：{timeline.specialYears.map((year) => `${year.label} ${year.year}`).join(' / ')}</p></div></section>
    <section className="relative isolate border border-line bg-surface p-5"><DefinitionSectionHeader id="numeric-definitions" title="共通数値定義" description="複数の経営指標から再利用する値を先に定義します。t・t-1等も式に直接記述できます。" addLabel="共通数値定義を追加" onAdd={() => change((draft) => draft.definitions.commonNumericDefinitions.push({ id: nextId('value', draft.definitions.commonNumericDefinitions.length), label: '新しい数値', formula: '0', outputPoint: 't' }))} /><div className="mt-3 grid grid-cols-2 gap-3">{program.definitions.commonNumericDefinitions.map((definition, index) => <article key={definition.id} className="grid gap-2 border-t-[3px] border-teal bg-background p-3"><div className="grid grid-cols-[1fr_36px] gap-2"><Input aria-label={`数値定義${index + 1} 名称`} value={definition.label} onChange={(event) => replaceProgram(renameNumericDefinition(program, definition.id, event.target.value))} /><Button variant="ghost" size="icon" aria-label={`${definition.label}を削除`} onClick={() => change((draft) => { draft.definitions.commonNumericDefinitions.splice(index, 1); })}><Trash2 /></Button></div><Textarea aria-label={`${definition.label} 計算式`} value={definition.formula} onChange={(event) => change((draft) => { draft.definitions.commonNumericDefinitions[index].formula = event.target.value; })} /></article>)}</div></section>
    <section className="relative isolate border border-line bg-surface p-5"><DefinitionSectionHeader id="management-metrics" title="経営指標・目標" description="制度目標と、個社目標を優先・下限・上限のどれとして扱うかを定義します。個社値そのものは案件JSONへ保存します。" addLabel="経営指標を追加" onAdd={() => change((draft) => draft.definitions.managementMetrics.push({ id: nextId('metric', draft.definitions.managementMetrics.length), label: '新しい経営指標', enabled: true, scope: 'company', timePoints: [{ id: 'A', anchor: { type: 'historicalEnd' }, offset: 0 }], formula: '0', outputUnit: '', target: 0, targetPolicy: 'reference', direction: 'min', optimization: 'fixed' }))} /><div className="mt-3 grid grid-cols-2 gap-3">{program.definitions.managementMetrics.map((metric, index) => <MetricCard key={metric.id} metric={metric} program={program} update={(next) => change((draft) => { draft.definitions.managementMetrics[index] = next; })} remove={() => change((draft) => { draft.definitions.managementMetrics.splice(index, 1); })} />)}</div></section>
  </main>;
}
